version: '3.8'

services:
    sqlserver:
        build: ./sql-server/
        # image: mcr.microsoft.com/mssql/server:2017-latest
        restart: always
        environment:
        - SA_PASSWORD=Pass@word
        - ACCEPT_EULA=Y
        ports:
        - "5434:1433"